const NEW_PRODUCT = "NEW_PRODUCT";
const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
const POST_PRODUCT = "POST_PRODUCT";
const NEW_MESSAGE = "NEW_MESSAGE";
const POST_MESSAGE = "POST_MESSAGE";
const UPDATE_MESSAGES = "UPDATE_MESSAGES";


module.exports = {
  NEW_PRODUCT,
  UPDATE_PRODUCTS,
  POST_PRODUCT,
  NEW_MESSAGE,
  POST_MESSAGE,
  UPDATE_MESSAGES
}
